version: "3.3"
services:
  nginx:
    image: nginx:latest
    command: nginx -g "daemon off;"
    links:
      - php
    ports:
      - "8001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      default:
        aliases:
          - nginx
  php:
    build: ./php
    volumes:
      - ./:/var/www/html
      - ./storage/logs:/var/www/html/storage/logs
    working_dir: /var/www/html/
    command: php-fpm
    depends_on:
      - redis
    ports:
      - "9001:9001"
    environment:
      REDIS_HOST: redis
    networks:
      default:
        aliases:
          - php-fpm
  redis:
    image: redis:alpine
    networks:
      default:
        aliases:
          - redis
