version: "3.3"
services:
  nginx:
    image: nginx:latest
    container_name: stat_nginx
    command: nginx -g "daemon off;"
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ulimits:
      nproc: 65535
      nofile:
        soft: 49999
        hard: 99999
  php:
    build: docker/php
    container_name: stat_fpm
    volumes:
      - ./:/var/www/html
      - ./storage/logs:/var/www/html/storage/logs
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www/html/
    environment:
      REDIS_HOST: redis
    ulimits:
      nproc: 65535
      nofile:
        soft: 49999
        hard: 99999
  php2:
    build: docker/php
    container_name: stat_fpm2
    volumes:
      - ./:/var/www/html
      - ./storage/logs:/var/www/html/storage/logs
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www/html/
    environment:
      REDIS_HOST: redis
    ulimits:
      nproc: 65535
      nofile:
        soft: 49999
        hard: 99999
  php3:
    build: docker/php
    container_name: stat_fpm3
    volumes:
      - ./:/var/www/html
      - ./storage/logs:/var/www/html/storage/logs
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www/html/
    environment:
      REDIS_HOST: redis
    ulimits:
      nproc: 65535
      nofile:
        soft: 49999
        hard: 99999
  redis:
    image: redis:alpine
