version: "3.3"
services:
  nginx:
    image: nginx:latest
    container_name: stat_nginx
    command: nginx -g "daemon off;"
    ports:
      - "8001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  php:
    build: ./php
    container_name: stat_fpm
    volumes:
      - ./:/var/www/html
      - ./storage/logs:/var/www/html/storage/logs
    working_dir: /var/www/html/
    environment:
      REDIS_HOST: redis
  redis:
    image: redis:alpine
